kumuluzee:
  name: pinger-supervisor
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count,X-Limit,X-Offset,X-Page-Token"
  openapi:
    enabled: true
    ui:
      enabled: true
  logs:
    loggers:
      - name: ''
        level: INFO
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      disk-space-health-check:
        threshold: 100000000
        type: liveness
mongo:
  username: mongo
  password: mongo
  host: localhost
  port: 27017
  database: supervisor
keycloak:
  realm: ping-pong
  auth-server-url: https://keycloak.mjamsek.com/auth
  client-id: supervisor-service
  auth:
    client-secret: not_set
web:
  client-id: supervisor-public
