pipeline {
    environment {
        registry = "https://docker.mjamsek.com"
        registryCredential = "nexus-username"
        dockerImageTag = "docker.mjamsek.com/pinger-supervisor"
        dockerImage = ""
        version = ""
        commitAuthor = ""
    }

    agent any

    tools {
        maven "mvn-3.6"
        nodejs "node-12"
        jdk "jdk-13"
    }

    stages {
        stage("Cloning git") {
            steps {
                git branch: "master",
                        credentialsId: "github-username",
                        url: "https://github.com/Jamsek-m/pinger-supervisor.git"
            }
        }
        stage("Set environment variables") {
            steps {
                script {
                    version = readFile('VERSION').trim()
                    sh "git --no-pager show -s --format='%ae' > COMMIT_INFO"
                    commitAuthor = readFile("COMMIT_INFO").trim()
                }
            }
        }
        stage("Packaging application") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-username', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh "mvn clean package -Dci.nexus.user=$USERNAME -Dci.nexus.pass=$PASSWORD --settings .ci/settings.xml"
                }
            }
        }
        stage("Building docker image") {
            steps {
                script {
                    dockerImage = docker.build dockerImageTag
                }
            }
        }
        stage("Publishing docker image") {
            steps {
                script {
                    docker.withRegistry(registry, registryCredential) {
                        dockerImage.push("1.0.0-SNAPSHOT")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage("Cleanup docker images") {
            steps {
                sh "docker rmi $dockerImageTag:1.0.0-SNAPSHOT"
                sh "docker rmi $dockerImageTag:latest"
            }
        }
    }
    post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' from ${commitAuthor} (${env.BUILD_URL})")
        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' from ${commitAuthor} (${env.BUILD_URL})")
        }
    }
}